fix(action-template): invalid parse of instal token etc

diff --git a/action-template.yml b/action-template.yml
--- a/action-template.yml
+++ b/action-template.yml
@@ -112,27 +112,41 @@ runs:
     - name: Run build script
       shell: bash
       env:
-        install-scope: '${{ inputs.install-scope }}'
-        install-token: '${{ inputs.install-token || inputs.npm-token }}'
-        install-registry-url: '${{ inputs.install-registry-url || inputs.registry-url }}'
+        ENTRY_POINT: ${{ inputs.entrypoint }}
+        INSTALL_REGISTRY_URL: '${{ inputs.install-registry-url || inputs.registry-url }}'
+        INSTALL_SCOPE: '${{ inputs.install-scope }}'
+        INSTALL_TOKEN: '${{ inputs.install-token || inputs.npm-token }}'
+        PLATFORM: ${{ inputs.platform }}
       run: |
-        install_scope='${{ env.install-scope }}'
-        install_token='${{ env.install-token }}'
-        install_registry_url='${{ env.install-registry-url }}'
+        if [ -n "$INSTALL_SCOPE" ]; then
+          echo "Creating bunfig.toml for private scope $INSTALL_SCOPE"
 
-        if [ -n "$install_scope" ]; then
-          echo "Creating bunfig.toml for private scope $install_scope"
+          should_exit=0
+
+          if [ -z "$INSTALL_TOKEN" ]; then
+            echo "Error: No token provided for private scope $INSTALL_SCOPE"
+            should_exit=1
+          fi
+
+          if [ -z "$INSTALL_REGISTRY_URL" ]; then
+            echo "Error: No registry URL provided for private scope $INSTALL_SCOPE"
+            should_exit=1
+          fi
+
+          if [ $should_exit -eq 1 ]; then
+            exit 1
+          fi
 
           cat <<EOF >bunfig.toml
           # bunfig.toml
           [install.scopes]
-          "$install_scope" = { token = "$install_token", url = "$install_registry_url" }
+          "$INSTALL_SCOPE" = { token = "$INSTALL_TOKEN", url = "$INSTALL_REGISTRY_URL" }
         EOF
 
-          echo "Creating .npmrc for private scope $install_scope"
+          echo "Creating .npmrc for private scope $INSTALL_SCOPE"
           cat <<EOF >.npmrc
-          $install_scope:registry=$install_registry_url
-          //npm.pkg.github.com/:_authToken=$install_token
+          $INSTALL_SCOPE:registry=$INSTALL_REGISTRY_URL
+          //npm.pkg.github.com/:_authToken=$INSTALL_TOKEN
         EOF
         else
           echo "No private scope provided for installation"
@@ -142,9 +156,6 @@ runs:
 
         echo "Cleaning up node auth tokens for bun and npm"
         rm -f bunfig.toml .npmrc
-      env:
-        PLATFORM: ${{ inputs.platform }}
-        ENTRY_POINT: ${{ inputs.entrypoint }}
 
     - name: Publish to npm or GitHub Packages
       if: ${{ inputs.publish }}
